import { SupportedLanguages } from '../src/types';
export const supportedLanguages: SupportedLanguages[] = [
  'bash',
  'c',
  'clojure',
  'cpp',
  'csharp',
  'dart',
  'elixir',
  'elm',
  'erlang',
  'fsharp',
  'graphql',
  'go',
  'groovy',
  'haskell',
  'html',
  'java',
  'javascript',
  'jsx',
  'julia',
  'kotlin',
  'lisp',
  'makefile',
  'matlab',
  'objectivec',
  'ocaml',
  'php',
  'python',
  'r',
  'ruby',
  'rust',
  'scala',
  'sql',
  'swift',
  'tsx',
  'typescript',
];

export const themeObj = {
  'a11y-dark': 'a11yDark',
  'a11y-light': 'a11yLight',
  'an-old-hope': 'anOldHope',
  androidstudio: 'androidstudio',
  arta: 'arta',
  'atom-one-dark': 'atomOneDark',
  'atom-one-light': 'atomOneLight',
  codepen: 'codepen',
  dracula: 'dracula',
  far: 'far',
  github: 'github',
  googlecode: 'googlecode',
  hopscotch: 'hopscotch',
  hybrid: 'hybrid',
  'ir-black': 'irBlack',
  'mono-blue': 'monoBlue',
  'monokai-sublime': 'monokaiSublime',
  monokai: 'monokai',
  nord: 'nord',
  obsidian: 'obsidian',
  ocean: 'ocean',
  'paraiso-dark': 'paraisoDark',
  'paraiso-light': 'paraisoLight',
  pojoaque: 'pojoaque',
  purebasic: 'purebasic',
  railscast: 'railscast',
  rainbow: 'rainbow',
  'shades-of-purple': 'shadesOfPurple',
  'solarized-dark': 'solarizedDark',
  'solarized-light': 'solarizedLight',
  sunburst: 'sunburst',
  'tomorrow-night-blue': 'tomorrowNightBlue',
  'tomorrow-night-bright': 'tomorrowNightBright',
  'tomorrow-night-eighties': 'tomorrowNightEighties',
  'tomorrow-night': 'tomorrowNight',
  tomorrow: 'tomorrow',
  vs2015: 'vs2015',
  xt256: 'xt256',
  zenburn: 'zenburn',
};

